# See: https://travis-ci.org/bendiken/nerves_grove

sudo: false

language: elixir
elixir:
  - 1.3.2
otp_release:
  - 19.0
script:
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis

notifications:
  slack:
    secure: BF/4x88nH9/kzs8zmeX60IxUy6pqX8oyBvc4FAZe+jOC5NPr+aIJwzT9ljfOFodiV5LisO/Il1QB/yspnYQxmoFZDouSmmk3XQTupKy5kcidOJyYvO7EQqPzQ0D9YaZN4egvQYh47cLs7SO1r9t7FoGG1QXJtn7fEwWyoBlS8mh4tdXTKPbepe58xjAoHFkf441k9QAXExzgM9AhxFNoeKdHV5Bs8fJfLTfRq9Wv1YWgO5l1LFZJ1eUS5gHoo0kcTt3QFf8A3qbcnJoEeSY5P7YSkpnCdMVRx4q2EzHut1OL81POJIrhCLCAf5I3zv5f0h8+NZkMbH8ycFYZ1NzEDg0EPickGyeMgwEBtaqdiiK/AH0y5YTZFQYpRW3iEvbUx5YH0Gl5JJYo1Bd4bM82zTdJDHXixqwz2DeHgspC0JDLfo56mWzNrejemPjFvL9r1/d72ZouueC2U56D+fW2U40Msx2jB0oQdDdNE77Pq+jKa+XkNLsu9ZcfqerTs6j6TGG21haZupdkGUqCdrLp1akGhtoRFdEy9AULyPgU3EbklJXL7K5YIHVwVS7KraGBVgNyNqn1afd/MP7iLPqKm94fj+U0SEkQuUIMEJUzrnMy2LcAu/+Qgl5rI9vekmkbly8n/s542R1o7wCk3NZStQrLzqvVG/cuqca0Ds9FSoU=
